### ISSUE TITLE
Can you offer us the file of LFW-masked?

### ISSUE THREAD

**Issue by sja9527** [amaan-akram/OpenVINO-FaceMaskDetection#1]
Can you offer us the file of LFW-masked or give us a link to download it?

**Comment by amaan-akram** [comment]
https://github.com/X-zhangyang/Real-World-Masked-Face-Dataset

**Comment by amaan-akram** [comment]
> Can you offer us the file of LFW-masked or give us a link to download it?

https://github.com/X-zhangyang/Real-World-Masked-Face-Dataset

**Comment by sja9527** [comment]
Thank you so much. But i gonna to find the structure of lfw-mask like lfw

**Comment by amaan-akram** [comment]
Hi, here is my structured version of LFW-Mask dataset that I organised using the provided python scripts in my repo. thanks,
https://drive.google.com/drive/u/0/folders/18E4khiih4kAWzixHm1z1xZc-VRA9UR-1

**Comment by sja9527** [comment]
Thank you so much .However, the link'https://drive.google.com/drive/u/0/folders/18E4khiih4kAWzixHm1z1xZc-VRA9UR-1' ,can not open. Its limited

**Comment by amaan-akram** [comment]
Sorry about that here you go 

https://drive.google.com/file/d/17JHo6qWW0ntbuXQRQWNJu91l8iDQVR0W/view?usp=sharing

**Comment by bocongju** [comment]
Sorry for disturbing you
I can't find it at https://www2.macs.hw.ac.uk/~aa322/dissertation/   Download your file
Can you provide it?
